# Generated by Django 4.2.5 on 2023-10-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_historias_playlist_rename_velero_suscriptos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historias',
            old_name='opinion',
            new_name='historia',
        ),
        migrations.RemoveField(
            model_name='historias',
            name='date',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='date',
        ),
    ]
