# Generated by Django 4.2.5 on 2023-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_rename_opinion_historias_historia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historias',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
