# Generated by Django 4.2.5 on 2023-10-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_historias_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reseñas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('opinion', models.CharField(max_length=200)),
                ('puntaje', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Historias',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
