# Generated by Django 4.2.5 on 2023-10-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_cafeterias_reseñas_delete_historias_delete_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscriptos',
            old_name='firs_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='suscriptos',
            name='date_of_birth',
        ),
    ]
