# Generated by Django 4.2.5 on 2023-10-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_rename_firs_name_suscriptos_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeterias',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
