# Generated by Django 4.2.5 on 2023-10-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_alter_cafeterias_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cafeterias',
        ),
    ]
