# Generated by Django 4.2.5 on 2023-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_remove_reseñas_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeterias',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
