# Generated by Django 4.2.5 on 2023-10-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_comentario_cafeteria_alter_comentario_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeterias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cafeterias_images/'),
        ),
    ]
