# Generated by Django 4.2.5 on 2023-10-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_cafeterias_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscriptos',
        ),
    ]
