# Generated by Django 4.2.5 on 2023-10-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0018_cafeterias_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
